### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by const-ae** [anna-neufeld/countsplit#3]
Hi Anna,

I just tried to install the `countsplit` and got an error message about a cyclic depedency:

```R
> devtools::install_github("anna-neufeld/countsplit")
Downloading GitHub repo anna-neufeld/countsplit@HEAD
Installing 1 packages: speedglm
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/speedglm_0.3-4.tgz'
Content type 'application/x-gzip' length 189246 bytes (184 KB)
==================================================
downloaded 184 KB


The downloaded binary packages are in
	/var/folders/dc/tppjxs9x6ll378lq88lz1fm40000gq/T//RtmpHRMq62/downloaded_packages
✔  checking for file ‘/private/var/folders/dc/tppjxs9x6ll378lq88lz1fm40000gq/T/RtmpHRMq62/remotes191c76361d24/anna-neufeld-countsplit-88af15d/DESCRIPTION’ (371ms)
─  preparing ‘countsplit’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts (2.4s)
─  checking for empty or unneeded directories
─  building ‘countsplit_1.0.tar.gz’
   
* installing *source* package ‘countsplit’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error : package or namespace load failed for ‘countsplit’ in loadNamespace(package, lib.loc):
 cyclic namespace dependency detected when loading ‘countsplit’, already loading ‘countsplit’
Error: unable to load R code in package ‘countsplit’
Execution halted
ERROR: lazy loading failed for package ‘countsplit’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/countsplit’
Warning messages:
1: replacing previous import ‘stats::filter’ by ‘dplyr::filter’ when loading ‘latin’ 
2: In i.p(...) :
  installation of package ‘/var/folders/dc/tppjxs9x6ll378lq88lz1fm40000gq/T//RtmpHRMq62/file191c37303370/countsplit_1.0.tar.gz’ had non-zero exit status
```

I am able to install an older version of the package (`devtools::install_github("anna-neufeld/countsplit@06139f6658027")`) and thus believe that #2 broke the package. In particular the file  [R/test_sparse_formulation](https://github.com/anna-neufeld/countsplit/blob/main/R/test_sparse_formulation.R) looks suspicious to me. I think you can fix the problem by moving that file to a test folder.

-------------

Relatedly, do you have any plans to submit your package to CRAN so that others (e.g., me) can depend on it?

Best,
Constantin

**Comment by anna-neufeld** [comment]
Hi Constantin,

Thank you so much for letting me know! That test file should not have been included in the R folder- that was a mistake! It should be fixed now, but please let me know if you have any additional issues with installation.

I previously did not submit to CRAN due to the CRAN rules about package size (the vignettes + data that are included are too large). However, it is good to know that it would be useful for dependencies if it was on CRAN. I know that there are many workarounds to the package size problem (e.g. = moving data to a separate package), so I will look into those and try to get this submitted to CRAN within the next few weeks.

Thanks!
Anna

**Comment by const-ae** [comment]
Hi Anna,

>  It should be fixed now, but please let me know if you have any additional issues with installation.

Yes, the installation now succeeds :)

> I previously did not submit to CRAN due to the CRAN rules about package size (the vignettes + data that are included are too large). However, it is good to know that it would be useful for dependencies if it was on CRAN. I know that there are many workarounds to the package size problem (e.g. = moving data to a separate package), so I will look into those and try to get this submitted to CRAN within the next few weeks.

Awesome.

-------

I also noticed that the package depends on `speedglm` however I couldn't find where that package is used. Is it a necessary dependency?
