### ISSUE TITLE
countsplit returns invalid object for sparse matrix

### ISSUE THREAD

**Issue by const-ae** [anna-neufeld/countsplit#4]
Hi Anna,

when I call `countsplit` using a `dgCMatrix`, it returns two `dgCMatrix` objects. However, the `train` matrix contains an integer vector and not a double vector which causes problems. See the example below:

``` r
library(Matrix)
mat <- matrix(0, nrow = 5, ncol = 10)
mat[2,2] <- 5L
sp_mat <- as(mat, "dgCMatrix")

tmp <- countsplit::countsplit(sp_mat)
validObject(tmp$test)
#> [1] TRUE
validObject(tmp$train)
#> Error in validObject(tmp$train): invalid class "dgCMatrix" object: 'x' slot is not of type "double"
```

<sup>Created on 2023-02-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I think the problem is [here](https://github.com/anna-neufeld/countsplit/blob/main/R/countsplit.R#L20) because `rbinom` returns integers. You could fix the problem by wrapping the statement in `as.numeric`.

---------

Furthermore, I noticed that you are currently checking for sparse matrices using `class(X) == 'dgCMatrix'`. This is fragile because an object can have more than one class, so I would recommend to change that to `is(X, "dgCMatrix")` or `is(X, "sparseMatrix")`. (I am not 100% sure which is the best super class to test for given that you expect a slot called `x`)

Best, Constantin

**Comment by anna-neufeld** [comment]
Thank you so much! 

I will fix these!!

Meanwhile, we are working on some big package updates to get this working for negative binomial count splitting as well (described briefly in this paper: https://arxiv.org/abs/2301.07276, a more specific scRNA-seq focused paper is in preparation). One of the holdups on this is that I'm not very good at working with sparse matrices, so my collaborator is helping out!!

Once we get this negative binomial function in working order, we will do a larger release and submit to CRAN !

**Comment by const-ae** [comment]
> Meanwhile, we are working on some big package updates to get this working for negative binomial count splitting as well (described briefly in this paper: https://arxiv.org/abs/2301.07276, a more specific scRNA-seq focused paper is in preparation). 

I saw the paper, I am very much looking forward to seeing the final product :)

> One of the holdups on this is that I'm not very good at working with sparse matrices, so my collaborator is helping out!!

Just in case you and your collaborator get stuck on something, I have worked quite a bit with sparse matrices for the [sparseMatrixStats](https://www.bioconductor.org/packages/devel/bioc/html/sparseMatrixStats.html) package, I'd be happy to help.

Best,
Constantin

**Comment by const-ae** [comment]
I saw that you fixed these issues in https://github.com/anna-neufeld/countsplit/commit/719b7ee41f27a1c19ba552458620d9922cee4028, so I will close this issue. 

Feel free to reopen, in case you kept it open for a reason.
