### ISSUE TITLE
class(X) error in countsplit()

### ISSUE THREAD

**Issue by munrosa** [anna-neufeld/countsplit#5]
Hello, I am working through your tutorial materials and there's an issue with some of the logic because of changes in R > 4.0.
I created the matrix X as in [your introductory tutorial](https://anna-neufeld.github.io/countsplit/articles/countsplit_tutorial.html)
I get the following error when I try to run countsplit:
```
> split <- countsplit(as.matrix(X), epsilon=0.5)
Error in if (class(X) == "dgCMatrix") { : the condition has length > 1
> class(X)
[1] "matrix" "array" 
```
A quick look at [stackoverflow](https://stackoverflow.com/questions/64660948/issue-with-creating-a-matrix-in-r) suggests that you can avoid this issue by using inherits instead of class, so you don't get an error if class returns more than one value.
Instead of if(class(X) == "dgCMatrix") using if(inherits(X,"dgCMatrix")) should fix the issue.

Best,
Sarah

**Comment by anna-neufeld** [comment]
Thank you! Fixing now!
