### ISSUE TITLE
`nb.countsplit` fails for sparse input

### ISSUE THREAD

**Issue by const-ae** [anna-neufeld/countsplit#6]
Hi Anna,

I just saw that you implemented a version of count split for negative binomially distributed data.

When I tried to run it on my own data, I got an error about `which`:

``` r
library(Matrix)
counts <- matrix(rnbinom(n = 5 * 10, mu = 1.1, size = 1/0.3), nrow = 5, ncol = 10)
counts <- as(counts, "dgCMatrix")
countsplit::nb.countsplit(counts, overdisp = rep(0.3, 5))
#> Error in which(Xtrain != 0, arr.ind = T): argument to 'which' is not logical
```

<sup>Created on 2023-03-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.1 RC (2022-06-17 r82503)
#>  os       macOS Big Sur ... 10.16
#>  system   x86_64, darwin17.0
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       Europe/Berlin
#>  date     2023-03-20
#>  pandoc   2.19.2 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cli           3.6.0   2023-01-09 [1] CRAN (R 4.2.0)
#>  countsplit    1.2     2023-03-20 [1] Github (anna-neufeld/countsplit@dd9152c)
#>  digest        0.6.31  2022-12-11 [1] CRAN (R 4.2.0)
#>  evaluate      0.20    2023-01-17 [1] CRAN (R 4.2.0)
#>  fastmap       1.1.1   2023-02-24 [1] CRAN (R 4.2.0)
#>  fs            1.6.1   2023-02-06 [1] CRAN (R 4.2.0)
#>  glue          1.6.2   2022-02-24 [1] CRAN (R 4.2.0)
#>  htmltools     0.5.4   2022-12-07 [1] CRAN (R 4.2.0)
#>  knitr         1.42    2023-01-25 [1] CRAN (R 4.2.0)
#>  lattice       0.20-45 2021-09-22 [1] CRAN (R 4.2.1)
#>  lifecycle     1.0.3   2022-10-07 [1] CRAN (R 4.2.0)
#>  magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.2.0)
#>  Matrix      * 1.5-3   2022-11-11 [1] CRAN (R 4.2.0)
#>  purrr         1.0.1   2023-01-10 [1] CRAN (R 4.2.0)
#>  R.cache       0.16.0  2022-07-21 [1] CRAN (R 4.2.0)
#>  R.methodsS3   1.8.2   2022-06-13 [1] CRAN (R 4.2.0)
#>  R.oo          1.25.0  2022-06-12 [1] CRAN (R 4.2.0)
#>  R.utils       2.12.2  2022-11-11 [1] CRAN (R 4.2.0)
#>  reprex        2.0.2   2022-08-17 [1] CRAN (R 4.2.0)
#>  rlang         1.0.6   2022-09-24 [1] CRAN (R 4.2.0)
#>  rmarkdown     2.20    2023-01-19 [1] CRAN (R 4.2.0)
#>  rstudioapi    0.14    2022-08-22 [1] CRAN (R 4.2.0)
#>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.2.0)
#>  styler        1.9.0   2023-01-15 [1] CRAN (R 4.2.0)
#>  vctrs         0.5.2   2023-01-23 [1] CRAN (R 4.2.0)
#>  withr         2.5.0   2022-03-03 [1] CRAN (R 4.2.0)
#>  xfun          0.37    2023-01-31 [1] CRAN (R 4.2.0)
#>  yaml          2.3.7   2023-01-23 [1] CRAN (R 4.2.0)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.2/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

I assume the problem is that you need to explicitly call `Matrix::which` in https://github.com/anna-neufeld/countsplit/blob/main/R/countsplit.R#L85

--------------
 
One additional question: in the literature the overdispersion of a negative binomial is sometimes specified using $\alpha$ or $\theta = 1/\alpha$. In your parameterization is the mean-variance relationship:

1. $\text{var} = \mu + \text{overdisp}  \mu^2$ or
2.  $\text{var} = \mu + 1/\text{overdisp}  \mu^2$?

**Comment by anna-neufeld** [comment]
Hi Constantin!

Thank you!! The function has been added but the tutorials/examples are forthcoming!

I will fix the "which" function error right now. 

The parameterization question will be addressed in the upcoming tutorials, but the answer is Var(X) = mu + mu^2/(overdisp). So a value of overdisp=infinity corresponds to the Poisson distribution.

I believe that our parameterization matches that of sctransform, but is the inverse of the one in glmGamPoi (let me know if I am mistaken!).

**Comment by const-ae** [comment]
> I will fix the "which" function error right now.

Great. Thanks for taking care of this so quickly :)

> The parameterization question will be addressed in the upcoming tutorials, but the answer is Var(X) = mu + mu^2/(overdisp). So a value of overdisp=infinity corresponds to the Poisson distribution.
> I believe that our parameterization matches that of sctransform, but is the inverse of the one in glmGamPoi (let me know if I am mistaken!).

Yes, Var(X) = mu + mu^2/(overdisp) corresponds to sctransform (and `dnbinom(mu=..., size=...)`). As you can guess, I prefer Var(X) = mu + overdisp * mu^2, because then *over*dispersion intuitively corresponds to the amount of extra dispersion compared with a Poisson random variable. But anyways, as long as it is clear from the documentation, it won't be a problem :)

I am very excited about this project, and I am looking forward to the tutorial and examples.
